# Generated by Django 3.0.5 on 2020-05-04 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent_cat',
        ),
        migrations.AddField(
            model_name='department',
            name='super_department',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paper.Department', verbose_name='父级部门'),
        ),
    ]
