# Generated by Django 3.0.5 on 2020-05-04 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paper', '0002_auto_20200504_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='pub_date',
            field=models.DateField(verbose_name='日报日期'),
        ),
    ]
